### ISSUE TITLE
internal reference fails, treated as file

### ISSUE THREAD

**Issue by isysd** [AnalyticalGraphicsInc/wetzel#8]
There seems to be no support for defining sub-schemas inside a document (i.e. in definitions with an '#/*' id. Wetzel thinks that the internal reference is a file, and goes looking on the system.

```
node node_modules/wetzel/bin/wetzel.js schema.json 
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '#/Snobject/getSchema'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at replaceRef (/snobject/node_modules/wetzel/lib/replaceRef.js:22:39)
    at replaceRef (/snobject/node_modules/wetzel/lib/replaceRef.js:29:32)
    at replaceRef (/snobject/node_modules/wetzel/lib/replaceRef.js:29:32)
    at Object.resolve (/snobject/node_modules/wetzel/lib/schema4Resolver.js:28:14)
    at generateMarkdown (/snobject/node_modules/wetzel/lib/generateMarkdown.js:31:30)
    at Object.<anonymous> (/snobject/node_modules/wetzel/bin/wetzel.js:22:22)
    at Module._compile (module.js:570:32)
```

Simplified json schema below.

```
{
 "$schema": "http://json-schema.org/draft-04/schema#",
 "type": "object",
 "title": "Snobject",
 "id": "#/Snobject",
 "description": "",
 "properties": {
  "getSchema": {
   "$ref": "#/Snobject/getSchema"
  },
  "version": {
   "$ref": "#/Snobject/version"
  },
  "license": {
   "$ref": "#/Snobject/license"
  }
 },
 "definitions": {
  "getSchema": {
   "title": "getSchema",
   "id": "#/Snobject/getSchema",
   "description": "Get the schema for this snobject.",
   "allOf": [
    {
     "$ref": "#/Snobject/Method"
    }
   ],
   "definitions": {
    "request": {
     "$ref": "#/Snobject/Request/NullRequest"
    },
    "response": {
     "$ref": "#/Snobject/Response/SchemaResponse"
    }
   }
  },
  "version": {
   "title": "version",
   "id": "#/Snobject/version",
   "description": "Since Snobjects are standalone apps, they can be versioned independently using [semantic versioning](http://semver.org).",
   "type": "string",
   "pattern": "^\\d*\\.\\d*\\.\\d*$",
   "default": "0.0.1"
  },
  "license": {
   "type": "string",
   "id": "#/Snobject/license",
   "description": "The [SPDX](http://spdx.org) string representation of the license for this snobject.",
   "default": "MIT"
  }
}
```

**Comment by isysd** [comment]
Possibly fixed by #7, if I'm reading that code correctly... Will test again when that is merged.

**Comment by pjcozzi** [comment]
Thanks @isysd!

CC @HowardWolosky for #7.

**Comment by isysd** [comment]
I tested and #7 does not address this issue. It does seem related, though... needs a deep dive at the PR code

**Comment by isysd** [comment]
I believe I know the proper way to handle this! We need to make use of this guy: https://github.com/BigstickCarpet/json-schema-ref-parser. It will handle the various types of refs, including files, circular, etc..

**Comment by matthidinger** [comment]
Any chance there's been some progress on this one? It seems most real-world schemas will use local $ref's

**Comment by pjcozzi** [comment]
@matthidinger I don't think anyone has looked at this, but contributions here are very well!
